version: '3.8'
services:
  webapp:
    restart: unless-stopped
    build: ./public
    ports:
      - 3000:${WEBAPP_PORT}
    volumes:
      - ./public:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - node_network
  
  server:
    restart: unless-stopped
    build: ./server
    ports:
      - 5000:${SERVER_PORT}
    volumes:
      - ./server:/usr/src/appserv
      - /usr/src/appserv/node_modules
    networks:
      - node_network   

  proxy:
    restart: unless-stopped
    image: nginx
    ports:
      - 80:${NGINX_PORT}
    depends_on:
      - webapp
    volumes:
      - ./public/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - node_network

networks:
  node_network:
